### ISSUE TITLE
State check endpoint seems to be failing

### ISSUE THREAD

**Issue by BjoernPetersen** [BjoernPetersen/MusicBot-Spotify#25]

**Comment by BjoernPetersen** [comment]
```
[DefaultDispatcher-worker-5] ERROR net.bjoernpetersen.spotify.playback.SpotifyPlayback - Could not check state
com.wrapper.spotify.exceptions.detailed.NotFoundException: Not Found
        at com.wrapper.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:304)
        at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:154)
        at com.wrapper.spotify.requests.AbstractRequest.getJson(AbstractRequest.java:117)
        at com.wrapper.spotify.requests.data.player.GetInformationAboutUsersCurrentPlaybackRequest.execute(GetInformationAboutUsersCurrentPlaybackRequest.java:35)
        at net.bjoernpetersen.spotify.playback.SpotifyPlayback.checkState(SpotifyPlayback.kt:82)
        at net.bjoernpetersen.spotify.playback.SpotifyPlayback$checkState$1.invokeSuspend(SpotifyPlayback.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by BjoernPetersen** [comment]
Seems like this is a problem on Spotify's side: https://github.com/spotify/web-api/issues/1160
